// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuPImSLtbMad5P7x9QIJTrwwr82HGOIF4',
    appId: '1:486486518113:web:fe149ef1efe64a371afd20',
    messagingSenderId: '486486518113',
    projectId: 'ac-itera',
    authDomain: 'ac-itera.firebaseapp.com',
    databaseURL: 'https://ac-itera-default-rtdb.firebaseio.com',
    storageBucket: 'ac-itera.appspot.com',
    measurementId: 'G-J2YLJN65HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAluklVj9MrBsLfeijws0F5MOmyGiSMkZg',
    appId: '1:486486518113:android:0b4bcf08b0bc8eac1afd20',
    messagingSenderId: '486486518113',
    projectId: 'ac-itera',
    databaseURL: 'https://ac-itera-default-rtdb.firebaseio.com',
    storageBucket: 'ac-itera.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACePjreIhtmM7GTqDYWZkxuhIfOINsPnU',
    appId: '1:486486518113:ios:316dcc87058d54331afd20',
    messagingSenderId: '486486518113',
    projectId: 'ac-itera',
    databaseURL: 'https://ac-itera-default-rtdb.firebaseio.com',
    storageBucket: 'ac-itera.appspot.com',
    iosBundleId: 'com.example.iteraMonitoringAc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACePjreIhtmM7GTqDYWZkxuhIfOINsPnU',
    appId: '1:486486518113:ios:316dcc87058d54331afd20',
    messagingSenderId: '486486518113',
    projectId: 'ac-itera',
    databaseURL: 'https://ac-itera-default-rtdb.firebaseio.com',
    storageBucket: 'ac-itera.appspot.com',
    iosBundleId: 'com.example.iteraMonitoringAc',
  );
}
